steps:

  - id: go_version
    name: "gcr.io/cloud-builders/go"
    args: ["version"]
    env: ["GOPATH=go"]   

  - id: go_build
    name: "gcr.io/cloud-builders/go"
    args: ["build","./desafios-devops/4-Final/src"]
    env: ["GOPATH=go"]     

  - id: go_test
    name: "gcr.io/cloud-builders/go"
    args: ["test","./desafios-devops/4-Final/src"]
    env: ["GOPATH=go"] 

  - id: "Building image from Dockerfile.prod"
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/app-go:$SHORT_SHA', '-f', 'Dockerfile.prod', '.']

  - id: "Pushing image"
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/app-go:$SHORT_SHA']  

  - id: "Adjusting deployment file - k8s"
    name: 'gcr.io/cloud-builders/gcloud'  
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        sed 's#img-app-deployment#gcr.io/$PROJECT_ID/app-go:$SHORT_SHA#g' desafios-devops/4-Final/deployment.yaml > desafios-devops/4-Final/deployment-new.yaml;
        cat desafios-devops/4-Final/deployment-new.yaml;

  - id: 'Deploying k8s' 
    name: 'gcr.io/cloud-builders/kubectl'   
    args:
      - 'apply'
      - '-f'
      - 'desafios-devops/4-Final/deployment-new.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-docker-laravel'    
  

