steps:

  - id: go_version
    name: "gcr.io/cloud-builders/go"
    args: ["version"]
    env: ["GOROOT=go"]   

  - id: go_test
    name: "gcr.io/cloud-builders/go"
    args: ["test","app"]
    env: ["GOROOT=go"]  

