FROM golang as builder
WORKDIR ./src
COPY ./src ./
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix .

FROM alpine:latest
WORKDIR /app/
COPY --from=builder ./ /app
EXPOSE 8000
ENTRYPOINT ["./app"]