steps:

  - id: go_version
    name: "gcr.io/cloud-builders/go"
    args: ["version"]
    env: ["GOPATH=go"]   

  - id: go_test
    name: "gcr.io/cloud-builders/go"
    args: ["test","app"]
    env: ["GOPATH=go"]  

  - id: go_run
    name: "gcr.io/cloud-builders/go"
    args: ["run","app"]
    env: ["GOPATH=go"]
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'go/Dockerfile', '-t', 'gcr.io/$PROJECT_ID/docker-go:latest', '.']
images: ['gcr.io/$PROJECT_ID/docker-go:latest']

